FROM node:alpine
WORKDIR '/app'
RUN npm i -g @nestjs/cli
RUN npm i -g cross-env
COPY package.json .
RUN npm install
RUN apk update -q && \
    apk add -q git
COPY . .
CMD ["cross-env", "NODE_ENV=dev", "nest", "start", "--debug", "0.0.0.0:9229", "--watch"]